### PR TITLE
Exclude indexs when delete unique constrains

### PR DESCRIPTION
**Pull request by henrikek**
Django migrations 1 (add field undone)
```
migrations.AddField(
            model_name='processtask',
            name='undone',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET_NULL, related_name='undone_task', to='WorkflowEngine.ProcessTask'),
)
```

Django migrations 2 (remove field undone)
```
migrations.RemoveField(
            model_name='processtask',
            name='undone',
)
```

Problem description, delete_unique tries to remove a constraint that has already been deleted. See results below:

constraints - 'ProcessTask_undone_id_9a3b7af0_uniq': {'columns': ['undone_id'], 'primary_key': False, 'unique': True, 'foreign_key': None, 'check': False, 'index': True, 'orders': ['ASC'], 'type': 'idx'}

delete_constraint: 
`ALTER TABLE [ProcessTask] DROP CONSTRAINT ProcessTask_undone_id_9a3b7af0_fk_ProcessTask_id]`

delete_index: 
`DROP INDEX [ProcessTask_undone_id_9a3b7af0_uniq] ON [ProcessTask]`

delete_unique: 
`ALTER TABLE [ProcessTask] DROP CONSTRAINT [ProcessTask_undone_id_9a3b7af0_uniq]`

Traceback (most recent call last):
```
  File "C:\ESSArch\pd\python\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\ESSArch\pd\python\lib\site-packages\sql_server\pyodbc\base.py", line 555, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]'ProcessTask_undone_id_9a3b7af0_uniq' is not a constraint. (3728) (SQLExecDirectW); [42000] Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Could not drop constraint. See previous errors. 3727)")
```

### CODE REVIEW

**Comment by OskarPersson** [comment]
A test demonstrating the change should be added before merging this.

Also, please use proper text formatting in the description to make it more readable, it's quite difficult to follow it as it is right now.

**Comment by henrikek** [comment]
I have now updated the described text with better formatting and code blocks.

I'm not sure how to make a good test case besides the description of this PR.

**Comment by OskarPersson** [comment]
See #39 and #47 (might be related to this PR) for examples for writing tests

**Comment by henrikek** [comment]
Added test migrations 👍 The successful running of the 2 new test migrations should be sufficient to test this PR.

**Comment by OskarPersson** [comment]
Just the lint errors left :)

**Comment by henrikek** [comment]
Fixed :)

**Pull request merged**
