### PR TITLE
Accept deferrable kwarg for schema editor SQL

### PR DESCRIPTION
**Pull request by davidjb**
Using the current `master` and trying to run migrations on Django 3.1.4 results in the following error:

```python
(0.102) QUERY = 'CREATE TABLE [wagtailcore_workflowtask] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [sort_order] int NULL, [task_id] int NOT NULL, [workflow_id] int NOT NULL)' - PARAMS = (); args=None
  Applying wagtailcore.0047_add_workflow_models...Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
[...]
  File "lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 808, in database_forwards
    schema_editor.add_constraint(model, self.constraint)
  File "lib/python3.8/site-packages/django/db/backends/base/schema.py", line 360, in add_constraint
    sql = constraint.create_sql(model, self)
  File "lib/python3.8/site-packages/django/db/models/constraints.py", line 118, in create_sql
    return schema_editor._create_unique_sql(
TypeError: _create_unique_sql() got an unexpected keyword argument 'deferrable'
```

This PR adds the keyword arg to the function definition so it will be accepted.  It also adjusts the implementation of this function to match that of the [BaseDatabaseSchemaEditor](https://github.com/django/django/blob/stable/3.1.x/django/db/backends/base/schema.py#L1110), checking for deferrable support and handling invalid situations.  The result is effectively the same, an empty string passed to the `Statement()` calls.

### CODE REVIEW

**Comment by honyczek** [comment]
This patch helped me to resolve issue #63

**Comment by OskarPersson** [comment]
Please rebase this against master and fix the failing tests on Django 2.2 and 3.0

**Comment by davidjb** [comment]
@OskarPersson sure, can do. Will be into next week some time when I’ll have an environment to work on it

**Comment by davidjb** [comment]
Rebased the PR and tests are now passing on 2.2 and 3.0.  Had to add a version number check since the Statement constructor requires `deferrable` in 3.1 but fails with the kwarg present in earlier versions.

**Comment by OskarPersson** [comment]
Thanks!

**Comment by HarryPotterDeveloper** [comment]
Thanks it worked for me

**Comment by svbfromnl** [comment]
Can you create a new build and update the package at https://pypi.org/project/django-mssql-backend/ ?
Until the package is updated https://github.com/ESSolutions/django-mssql-backend/issues/63 will remain out there in the wild. I just ran into it today.

**Comment by davidjb** [comment]
@svbfromnl https://github.com/microsoft/mssql-django features this fix (just not backwards compatible for < Django 3.1 at the moment); installable via PyPI @ https://pypi.org/project/mssql-django/. 

I've opened https://github.com/microsoft/mssql-django/pull/9 to re-add support for older Django.

**Comment by tlugo-deacero** [comment]
@davidjb Thanks for this fix! However, the current version of `mssql-django 1.0a5` does not contain the feature. Could you build the package with it?

**Comment by davidjb** [comment]
@tlugo-deacero As best I can tell it does (https://github.com/microsoft/mssql-django/blob/dev/mssql/schema.py#L704-L706) -- just that it's not backwards compatible with < Django 3.1.  I switched my active project over to using `mssql-django` and my migrations and database ORM run okay without the errors seen here.

**Edit:** oh, I see what you mean -- the packaged version doesn't have it.  In that case, definitely [raise an issue](https://github.com/microsoft/mssql-django/issues) over there to ask Microsoft.

Note that I'm not a maintainer of that package, just a contributor -- https://github.com/microsoft/mssql-django/pull/9 (to add Django < 3.1 support as was added here in #86) isn't yet merged so feel free to add a comment or 👍 over there.

**Comment by legioz** [comment]
This issue is stille happening to me, Im using Django 3.1
image

**Comment by legioz** [comment]
> @svbfromnl https://github.com/microsoft/mssql-django features this fix (just not backwards compatible for < Django 3.1 at the moment); installable via PyPI @ https://pypi.org/project/mssql-django/.
> 
> I've opened [microsoft/mssql-django#9](https://github.com/microsoft/mssql-django/pull/9) to re-add support for older Django.

The last version is from 2016
The package looks a bit deprecated

**Comment by davidjb** [comment]
@luizfelipevbll Last version of mssql-django is out from 19 Mar 2021 (https://pypi.org/project/mssql-django/#history) - it's being actively worked on and I use it with Django 3.1 at present.

**Comment by legioz** [comment]
> @luizfelipevbll Last version of mssql-django is out from 19 Mar 2021 (https://pypi.org/project/mssql-django/#history) - it's being actively worked on and I use it with Django 3.1 at present.

Shit, I was looking in the wrong pkg django-mssql istead of mssql-django

Is [mssql-django 1.0b1](https://pypi.org/project/mssql-django/1.0b1/) stable for production?
Does it support django 3.2?

**Comment by davidjb** [comment]
@luizfelipevbll Not with that latest packaged version, no -- doesn't support Django 3.2 and has issues with certain DB/ORM operations (in particular you'd be interested in https://github.com/microsoft/mssql-django/pull/9 which re-adds on aspect of Django 3.1 support). The dev version has these fixes, plus those that fix https://github.com/microsoft/mssql-django/issues/25 for Django 3.2 support.  I'm not using Django 3.2 at this point, so can't comment more than I've read on the issue tracker.

**Pull request merged**
