### PR TITLE
Fix inspectdb

### PR DESCRIPTION
**Pull request by aceofwings**
Pull Request with Skipped Tests Removed. 

Field Info was included from earlier versions of Django since collation support was added, thus breaking introspection.

### CODE REVIEW

**Comment by OskarPersson** [comment]
Please don't open new PRs when making changes. Just push the changes to your branch in your fork and the PR is updated automatically.

**Comment by aceofwings** [comment]
Apologies, I just made a mistake on my commit history and made the quick decision to remove the branch. Anyways I removed 2 skipped tests under inspectdb.

**Comment by aceofwings** [comment]
Pushed changes include adding Positive Integer Field. I think this resolves most of the issues.

**Comment by OskarPersson** [comment]
Thanks!

**Pull request merged**
