### PR TITLE
Add Django 3 support

### PR DESCRIPTION
**Pull request by OskarPersson**

### CODE REVIEW

**Comment by wdifruscio** [comment]
excited to try out django 3.0! Do you need any help with this? Would be happy to contribute

**Comment by OskarPersson** [comment]
@wdifruscio Yes, definitely! I haven't had much time to look into how much of the errors that are left, lately I've just tried to setup a test suite that works at all for both Django 22 and Django 30, Python 36-38 on Linux and Windows. Though today Microsoft seems to have some issues with their Linux package repo so the Linux tests doesn't work att all at the moment but the Windows tests fails to clone Django for some unknown reason.

It would be great to get some help with both the code and test environment :)

**Comment by elramus** [comment]
Any updates on this? FWIW, this branch works fine for me in my own testing. Django is talking to MS SQL with no problems. Thanks!

**Comment by OskarPersson** [comment]
@elramus Not much, still not sure how to solve the errors in the Windows builds

**Comment by breaddevil** [comment]
Hello @OskarPersson, thank you for your work.

I managed to make the tests run on windows using trial and error and actions/checkout@v2 (it supports nested repositories):

https://github.com/ESSolutions/django-mssql-backend/compare/dj3...breaddevil:breaddevil-patch-1 #diff-90829e76e906f1c73140c7ded7e1b268R70 .

On the other hand it does not fetch all django branches so I did it in test.sh https://github.com/ESSolutions/django-mssql-backend/compare/dj3...breaddevil:breaddevil-patch-1 #diff-1b531c5e405e0bc95890d52cf2f2f5b5R11

I am not familiar with tox nor github workflows so I have no idea what the best practices are. The tests take a long time to run because of the pulling of the docker images for sql server.

Some tests are failing but as I could not manage to run the tests on my local machine I gave up. https://github.com/breaddevil/django-mssql-backend/pull/2/checks?check_run_id=397627503

**Comment by OskarPersson** [comment]
@breaddevil I will try this, thank you for your help!

**Comment by OskarPersson** [comment]
I've got the Windows builds working (thanks again @breaddevil). The next step is to identify the tests that needs to be fixed (and fix them) to get to an acceptable state before merging.

I appreciate all the help I can get.

**Pull request merged**
